services:
  mariadb:
    image: mariadb
    restart: always
    expose:
      - ${DB_PORT}  
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - minha-rede

  api:
    build: .
    restart: always
    expose:
      - ${DB_PORT_LOCAL}
    env_file:
      - .env
    environment:
      - NODE_ENV=docker  
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mariadb
    networks:
      - minha-rede

volumes:
  mariadb_data:

networks:
  minha-rede:
